# Generated by Django 4.2.11 on 2024-04-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
