# Generated by Django 4.2.11 on 2024-04-20 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_alter_playlists_user_songreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songreview',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
