# Generated by Django 4.2.11 on 2024-04-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0004_alter_songreview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
