# Generated by Django 4.2.11 on 2024-04-22 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0005_song_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='average_rating',
        ),
    ]
