# Generated by Django 4.2.11 on 2024-04-22 22:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0006_remove_song_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songreview',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
