# Generated by Django 4.2.11 on 2024-04-29 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0008_artistreview_albumreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtistReview',
        ),
    ]
